name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --release

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cargo pkgid | cut -d '#' -f2)" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        draft: false
        prerelease: false
        files: ./target/release/calc-distance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}